unique_ids:
  assets:
    standard-page.html: Y3ZYAGVEHU5EQM4JNCM4UXSCOCHCAGW3
    theme.css: LARTX2UXHN6JHTRLUALUAQWUBSYELGOR
  forms:
    Form1: 3KEJIS2DWRU3JXTZMYFVJXYPKWV3HORA
  modules: {}
  scripts: {}
  server_modules: {}
